# Generated by Django 2.1 on 2021-03-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='car_desc',
            new_name='cat_desc',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='car_img',
            new_name='cat_img',
        ),
    ]
