# Generated by Django 2.1 on 2021-03-28 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0002_auto_20210328_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='media')),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('uname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('occupation', models.TextField(max_length=250)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('update_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
