# Generated by Django 2.1 on 2021-07-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_auto_20210702_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpatient',
            old_name='patient_price',
            new_name='patient_address',
        ),
        migrations.RenameField(
            model_name='addpatient',
            old_name='patient_desc',
            new_name='patient_gender',
        ),
        migrations.RenameField(
            model_name='addpatient',
            old_name='selling_price',
            new_name='patient_number',
        ),
    ]
