# Generated by Django 2.1 on 2021-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0008_auto_20210702_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpatient',
            name='patient_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=250),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='patient_img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
