# Generated by Django 2.1 on 2021-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='patient_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
