# Generated by Django 2.1 on 2021-07-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0012_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpatient',
            name='seller',
        ),
        migrations.AddField(
            model_name='addpatient',
            name='appointment_sent',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='addpatient',
            name='patient_problem',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='added_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
