# Generated by Django 2.1 on 2021-07-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0013_auto_20210705_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpatient',
            name='appointment_sent',
        ),
    ]
