# Generated by Django 2.1 on 2021-07-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0014_remove_addpatient_appointment_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpatient',
            name='dateof_appointment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
