# Generated by Django 2.1 on 2021-07-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0015_addpatient_dateof_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpatient',
            name='patient_img',
        ),
    ]
