# Generated by Django 3.2 on 2022-01-03 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0017_auto_20220102_0806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='patient_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='patient_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='patient_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addpatient',
            name='patient_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='added_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_desc',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_img',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='added_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='occupation',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='update_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='screening',
            name='attendence',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='join',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='phone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='salary',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='tax',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='screening',
            name='work',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
