# Generated by Django 4.0.5 on 2022-06-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0019_auto_20220103_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screening',
            new_name='Employee',
        ),
    ]
