# Generated by Django 4.0.5 on 2022-06-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0021_delete_addpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='attendence',
        ),
    ]
