# Generated by Django 4.0.5 on 2022-07-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0025_alter_attendance_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.CharField(max_length=250)),
                ('attendece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.attendance')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockapp.employee')),
            ],
        ),
    ]
