# Generated by Django 4.0.5 on 2022-07-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0026_totalsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='totalsalary',
            name='leaverate',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
