# Generated by Django 4.0.5 on 2022-07-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0027_employee_overtime_totalsalary_leaverate'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalsalary',
            name='overtimerate',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
