# Generated by Django 4.0.5 on 2022-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0028_totalsalary_overtimerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(max_length=250, null=True),
        ),
    ]
