# Generated by Django 4.0.5 on 2022-07-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0031_rename_overtime_employee_overtimehour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='no_of_leave_day',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
