# Generated by Django 4.0.5 on 2022-07-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0032_attendance_no_of_leave_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='no_of_leave_day',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus',
            field=models.CharField(default='3%', max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='no_of_leave_day',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TotalSalary',
        ),
    ]
