# Generated by Django 4.0.5 on 2022-07-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0033_remove_attendance_no_of_leave_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work',
        ),
    ]
