# Generated by Django 4.0.5 on 2022-07-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0034_remove_employee_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
