# Generated by Django 4.0.5 on 2022-07-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0035_remove_employee_email_remove_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.CharField(max_length=250),
        ),
    ]
