# Generated by Django 4.0.5 on 2022-07-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0036_alter_employee_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.FloatField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join',
            field=models.CharField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='no_of_leave_day',
            field=models.FloatField(default=0, max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overtimehour',
            field=models.FloatField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax',
            field=models.FloatField(default=0, max_length=250),
        ),
    ]
