# Generated by Django 4.0.6 on 2022-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0038_employee_work_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='join',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='no_of_leave_day',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='overtimehour',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
