# Generated by Django 4.0.6 on 2022-09-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0039_remove_employee_bonus_remove_employee_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_status',
            field=models.CharField(choices=[('Parttime', 'Partime'), ('NormalTime', 'Normaltime'), ('OverTime', 'Overtime')], max_length=250),
        ),
    ]
