# Generated by Django 4.0.6 on 2022-09-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0042_remove_attendance_user_attendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bankamount',
            field=models.FloatField(default=323),
            preserve_default=False,
        ),
    ]
