# Generated by Django 4.0.6 on 2022-09-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0043_employee_bankamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='no_of_absent_days',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bankamount',
            field=models.FloatField(default=0),
        ),
    ]
