# Generated by Django 4.0.6 on 2022-09-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0044_employee_no_of_absent_days_alter_employee_bankamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='no_of_absent_days',
        ),
        migrations.AddField(
            model_name='attendance',
            name='no_of_absent_days',
            field=models.FloatField(default=0),
        ),
    ]
