# Generated by Django 4.0.6 on 2022-09-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0047_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime', to='stockapp.employee'),
        ),
    ]
