# Generated by Django 4.0.6 on 2022-09-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0049_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='bonus_price',
            field=models.FloatField(default='12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bonus',
            name='occation',
            field=models.CharField(max_length=250),
        ),
    ]
