# Generated by Django 4.0.6 on 2022-09-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0050_bonus_bonus_price_alter_bonus_occation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_price',
            field=models.FloatField(default=0),
        ),
    ]
